#!/usr/bin/env python3

def convert_mac_to_eui(mac, prefix="fe80::"):
                eui64 = mac.replace(":", "")
                eui64 = eui64[0:6] + 'fffe' + eui64[6:]
                eui64 = hex(int(eui64[0:2], 16) ^ 2)[2:].zfill(2) + eui64[2:]
                return prefix + ":" + ':'.join(eui64[i:i + 4] for i in range(0, len(eui64), 4))

if __name__ == "__main__": 
    #subnet for ESX VMs
    #subnet="2a0c:5bc0:89:ae2"
    #subnet for BMC
    subnet="2a0c:5bc0:89:b01"
    #subnet for rack
    #subnet="2a0c:5bc0:89:a11"
    mac="08:8f:c3:a2:6c:6c"
    print(convert_mac_to_eui(mac, subnet))
